[build-system]
requires = ["maturin>=1.4"]
build-backend = "maturin"

[project]
name = "knock-on-gpus"
description = "Check if GPUs are available before running your script that uses GPUs."
requires-python = ">=3.7"

[tool.maturin]
bindings = "bin"
strip = true
